### ISSUE TITLE
Navigation: "Community" in "Über uns" umbennen

### ISSUE THREAD

**Issue by arnese** [okfde/old.okfn.de#19]

**Comment by pudo** [comment]
Laaangweilig. Das hätte der Clou der Webseite sein können.

**Comment by stefanw** [comment]
@juliakloiber @ddie @arduina 
Ich bin auch für Community, ggf. + eine Über uns Seite.

Es wäre schon ein echt ein Move, wenn wir Community prominent darstellen.

**Comment by stefanw** [comment]
Nicht mehr Milestone relevant. Wird auf die nächste Überarbeitung verschoben.
Der Menüpunkt fehlt mangels Beteiligung.
