### ISSUE TITLE
Projektseite: Button zum "Projekt"

### ISSUE THREAD

**Issue by juliakloiber** [okfde/old.okfn.de#20]
Auf den Projektseiten unter dem Bescheribungstext einen großen Button "zur Projektwebsite" einfügen.

**Comment by stadine** [comment]
Ich bin dagegen. Dann stünde teilweise dreimal nebeneinander der Button „Zur Projektwebsite“. Das ist vielleicht ein bisschen zu viel des Guten.

Es geht ja darum, dass der Nutzer merkt, dass man da klicken kann. Dafür gibt es bereits einen Hover für die ganze Box: das Bild zoomt näher ran und die Schrift färbt sich um.  Ich denke, dass diese Veränderung reicht um zu merken „Hej, da kann ich klicken“. „Zeit online“ verzichtertmittlerweile auch schon auf den „mehr“ oder „Zum Artikel“ Button

**Comment by stefanw** [comment]
Ich glaube, ihr meint unterschiedliche Dinge. @stadine meint die Boxen in der Projektliste, @juliakloiber meint die Projektdetailseite unter dem Text. Die Projektdetailseite ist noch nicht fertig, gerade der untere Bereich nicht!

**Comment by ffalt** [comment]
großer knopf "Zur Projektwebseite" hinzugefügt
