### ISSUE TITLE
Spendenbutton

### ISSUE THREAD

**Issue by juliakloiber** [okfde/old.okfn.de#21]

**Comment by stadine** [comment]
den wollte ich im Folter unterbringen (genauso den newsletter) 
![04_okfn_projektdetail_02](https://cloud.githubusercontent.com/assets/7421063/6248013/5a4b5280-b77b-11e4-958a-b33fc8430ed7.jpg)

**Comment by stadine** [comment]
footer....nicht folter

**Comment by mneuschaefer** [comment]
da ist er sehr versteckt, bei dem Thema Grundfinanzierung bringt uns ein sichtbarer Action Button auf der Startseite weiter, möglichst im Umfeld von Vertrauenssignalen /Partnerlogos

**Comment by pudo** [comment]
Ich würde den nur auf zwei Seiten bringen: Home und Über uns. Dafür dann aber wirklich, wirklich groß und mit einem persönlichen Appeal (Wikipedia-style).

**Comment by ffalt** [comment]
spenden-banner ist auf startseite und link zu spenden-seite prominent im menü
