### ISSUE TITLE
Team- und Vorstand-Infos aktualisieren

### ISSUE THREAD

**Issue by stefanw** [okfde/old.okfn.de#28]
# Profile auf [Team-](https://okfde.github.io/okfn.de/team/) und [Vorstandsseite](https://okfde.github.io/okfn.de/vorstand/) anpassen
## So geht's
1. [Zum Team-Datensatz gehen](https://github.com/okfde/okfn.de/blob/gh-pages/_data/team.yaml)
2. Auf das Bearbeiten-Symbol klicken
3. Seinen Teil finden und bearbeiten.
4. Commiten
5. Unten abhaken, wenn fertig.
- [x] @knutator2 
- [x] @mneuschaefer 
- [x] @arnese 
- [x] @Pauletta 
- [x] @seegerseeger 

Folgende Leute sollten ihre Bio updaten und/oder kürzen:
- [ ] @ddie 
- [ ] @juliakloiber 
- [ ] @pudo

Und alle anderen auch mal drüber schauen

Bilder in Reihenfolge der Unangepasstheit zum Rest:
1. [ ] Andi P.
2. [ ] Marcus D.
3. [ ] Sören A.
4. [ ] Rufus P. (@rgrp)

**Comment by mneuschaefer** [comment]
gibt es irgendein System bei der Reihenfolge (Team/Vorstand , alphabet. Nachname etc)?

**Comment by stefanw** [comment]
mh, alphabetisch nach vollem Namen. Leider sind dann gerade Prof. unter "P" eingeordnet. Ich schau mal drauf, was man da machen kann.

**Comment by stefanw** [comment]
@mneuschaefer Dr. und Prof. sind jetzt richtig nach Vornamen geordnet.
