### ISSUE TITLE
Services / Training

### ISSUE THREAD

**Issue by pudo** [okfde/old.okfn.de#3]
Das ist ein wenig Organisationsentwicklung, was sind unsere kommerziellen Produkte?

ping / @data_meining @ddie

**Comment by m-hoerz** [comment]
Wie meinst du mit "ist ein wenig Organisationsentwicklung"?

Wo würdest du Trainings hinschieben?

**Comment by stefanw** [comment]
Die Idee war bisher unter Services folgende Dinge unterzubringen:
- generelle Beratung
- Training
- Haushaltsvisualisierung
- CKAN?
- Hack Days?

@ddie ist die Liste so vollständig?

**Comment by ffalt** [comment]
Text wurde von Arne, Helene & Walter überarbeitet
