### ISSUE TITLE
Jugend hackt background image: contrast

### ISSUE THREAD

**Issue by stefanw** [okfde/old.okfn.de#34]
@Pauletta @maliena Euer [aktuelles Hintergrundbild](https://okfde.github.io/okfn.de/projekte/jugendhackt/) hat leider nicht so viel Kontrast, so dass das Menü nicht mehr gut angezeigt wird (schwarzes Menü geht auch nicht).

Wollt ihr nicht doch lieber das hier nehmen?
https://www.flickr.com/photos/okfde/9722853923/in/set-72157635430259351

**Comment by Pauletta** [comment]
Jep, hast du recht. Aber vielleicht eher das. Da schauen die Leute netter :) https://www.flickr.com/photos/okfde/9732249824/in/set-72157635430259351
