### ISSUE TITLE
bunte auswahl an codefor-projektbildern

### ISSUE THREAD

**Issue by stadine** [okfde/old.okfn.de#38]
1, 2 oder 3? Oder ganz andere Vorschläge.

![code_1](https://cloud.githubusercontent.com/assets/7421063/6334871/a8b12fe2-bb97-11e4-9061-dea6876b4e8d.jpg)
![code_2](https://cloud.githubusercontent.com/assets/7421063/6334873/a8b5ec4e-bb97-11e4-8b51-a38ca40eeb03.jpg)
![code_3](https://cloud.githubusercontent.com/assets/7421063/6334872/a8b4353e-bb97-11e4-8015-ca0ae075d6ee.jpg)

**Comment by stefanw** [comment]
@arduina @juliakloiber Wählt mal aus, habe erstmal das rote genommen.

**Comment by stefanw** [comment]
Game over, es ist jetzt das rote geworden.
