### ISSUE TITLE
Blogposts auf der Startseite nicht so schön

### ISSUE THREAD

**Issue by christianheise** [okfde/old.okfn.de#44]
Hallo,

vielleicht könnte man die Blogposts wie die Projekte oben aussehen lassen (drei nebeneinander). 

Liebe Grüße,
Christian

**Comment by stefanw** [comment]
Leider sind die Blogpost-Bilder alle klein und doof, deswegen ist eine Ansicht mit schönem Bild ausgeschlossen. Das aktuelle Design macht die Bilder extra klein, dass die Häßlichkeit der Bilder nicht auffällt, aber die Wiedererkennbarkeit da ist.

**Comment by christianheise** [comment]
Hey, die Bilder liegen meist auch in anderen, viel größeren Formen vor - du musst du den Dateinamen modifizieren.

Z.B. http://de.okblogfarm.org/files/2015/02/buendnis-freie-bildung-415x76.png gibt es auch in http://de.okblogfarm.org/files/2015/02/buendnis-freie-bildung.png.

Liebe Grüße

**Comment by christianheise** [comment]
kann man das nicht als 6 Boxen wie bei den Projekten bauen + "weitere Posts lesen"-Link
siehe: 
![bildschirmfoto 2015-04-03 um 20 13 51](https://cloud.githubusercontent.com/assets/3036990/6986492/08ca0f24-da3e-11e4-87f2-ce002b594297.png)

Gern scribble ich die kommenden Tage mal ein Beispiel.

**Comment by stefanw** [comment]
Ok, einige Bilder gibt's auch in groß und schön, das ist aber leider absolut nicht garantiert und kann man schlecht für die Vergangenheit nachvollziehen.

Ich könnte mir vorstellen, die letzten drei Blogposts so darzustellen und den Rest etwas schlichter.

**Comment by christianheise** [comment]
Ja, klingt doch super.

**Comment by ffalt** [comment]
erledigt
