### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [okfde/old.okfn.de#48]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by pudo** [comment]
FWIW, https://github.com/okfde/okfn.de/blob/gh-pages/_includes/footer.html#L42

**Comment by karan** [comment]
Oh. I think that just applies to the content of the website but I could be wrong.

**Comment by stefanw** [comment]
Since this is jekyll page there's mostly content. Put I will add a license for good measure.

**Comment by karan** [comment]
Thanks
