### ISSUE TITLE
Hintergrund-Bilder/Videos für Seiten und Projekte

### ISSUE THREAD

**Issue by stefanw** [okfde/old.okfn.de#5]
Folgende Seiten brauchen große Hintergrund-Bilder oder Videos:
- [ ] Homepage
- [x] Themen
  - [ ] Civic Technology
  - [x] Informationsfreiheit
  - [ ] Offene Daten
  - [x] Offene Kulturgüter
  - [ ] Civic Technology
  - [ ] Offene Wissenschaft
- [x] Projekte
- [x] Community
  - [x] Team
- [x] Blog
- [x] Services

Und natürlich am Besten jedes Projekt.

Bitte submitted eure schönen, großformatigen Bilder hier als Kommentare (oder direkt ins Git).

**Comment by maliena** [comment]
Community: https://www.flickr.com/photos/okfde/9504145654/in/set-72157635058900648 
- Lizenz: CC BY 2.0 Open Knowledge Foundation Deutschland

**Comment by maliena** [comment]
Jugend hackt: https://www.flickr.com/photos/okfde/9732252066/in/set-72157635430259351
- Lizenz: CC BY 2.0 Open Knowledge Foundation Deutschland

**Comment by maliena** [comment]
Themen: https://www.flickr.com/photos/okfde/13937447117/in/set-72157644136004990
- Lizenz: CC BY 2.0 Volker Agueras Gäng

**Comment by maliena** [comment]
Projekte: https://www.flickr.com/photos/okfde/13150643523/in/set-72157642349149383
- Lizenz: CC BY 2.0 Open Knowledge Foundation Deutschland

**Comment by maliena** [comment]
Services: https://www.flickr.com/photos/okfde/9501204047/in/set-72157635052259499 
- Lizenz: CC BY 2.0 Open Knowledge Foundation Deutschland

ODER

https://www.flickr.com/photos/okfde/9504053216/in/set-72157635052459161
- Lizenz: CC BY 2.0 Open Knowledge Foundation

**Comment by maliena** [comment]
Offene Kulturgüter: https://www.flickr.com/photos/okfde/13561127984/in/set-72157643263439724
- Lizenz: CC BY 2.0 Ostberliner Fotoarchiv - Berlinische Galerie, Urheberin: Gisela Dutschmann

**Comment by maliena** [comment]
Blog: https://www.flickr.com/photos/okfde/9504056192/in/set-72157635052459161
- Lizenz: CC BY 2.0 Open Knowledge Foundation

**Comment by maliena** [comment]
Team: Das Standup-Foto von Fiona (ich weiß nicht, wo die liegen)
- Lizenz: CC ... Fiona Krakenbürger

**Comment by christianheise** [comment]
Offene Wissenschaft: 
https://www.dropbox.com/s/nv2o2dhee5d3qiz/69H.jpg?dl=1
Lizenz: Public Domain 

via http://www.gratisography.com/

**Comment by arnese** [comment]
Informationsfreiheit: https://www.flickr.com/photos/foto_db/13837286873
- Lizenz: CC-BY-NC 2.0 Tim Reckmann

(grad gesehen: gibt ja schon luftballons dort, die sind auch schön.)

**Comment by stefanw** [comment]
LGTM, mostly.
