### ISSUE TITLE
Blog: Autorbild für "OKF"

### ISSUE THREAD

**Issue by arnese** [okfde/old.okfn.de#66]
Bisher sind nur einzelne Personen als Blogautor mit Bild versehen. Bei kollaborativen generellen Posts wäre es schön, wenn der Autor "OKF" als Autorenbild das OKF-Logo kriegen könnte.
Umsetzung: Vielleicht OKF als unsichtbares Teammitglied oder so.

**Comment by ffalt** [comment]
genau so umgesetzt: als unsichtbares teammitglied
ausserdem können nun auch mehrere autor*innen angegeben werden, für die dann je ein bild erscheint
