### ISSUE TITLE
Frühere Mitglieder von Team und Board darstellen

### ISSUE THREAD

**Issue by stefanw** [okfde/old.okfn.de#68]

**Comment by arnese** [comment]
Eher auf einer Extra-Seite als auf der selben Seite mit aktiven Mitgliedern, oder?

**Comment by christianheise** [comment]
jup

**Comment by knutator2** [comment]
Es gibt jetzt eine Extraseite für den Vorstand. Wollen wir sowas auch fürs Team? Wird dann ziemlich voll
