### ISSUE TITLE
Unterseite "Family & Friends"?

### ISSUE THREAD

**Issue by arnese** [okfde/old.okfn.de#70]
Wäre eine Möglichkeit, um ein paar unserer Unterstützer und wohlgesonnener Partner darzustellen. Vielleicht sinnvoll?

**Comment by ffalt** [comment]
erstellst du eine liste? dann leg ich die seite an und suche die logos, etc.

**Comment by arnese** [comment]
- headissue - Kooperation mit kleineAnfragen.de
- Stromnetz Berlin  @heleneh  - reinnehmen?)
- Deutsche Bahn @vavoida - reinnehmen?)
- SenWTF @heleneh  - reinnehmen?)
- Partner bei OParl hier reinnehmen, @the-infinity ?
- Sollen hier CodeFor-Partner stehen, @juliakloiber ?
- OKF international

**Comment by Pauletta** [comment]
- mediale pfade
- mabb
- bpb

**Comment by arnese** [comment]
Zumindest vorübergehend durch Einbindung bei Services gelöst.
