### ISSUE TITLE
Themen-Seite „Offene Kulturgüter“

### ISSUE THREAD

**Issue by stefanw** [okfde/old.okfn.de#8]
Text, großes Hintergrundbild und ggf. andere Bilder, Pull Quotes.

**Comment by stefanw** [comment]
Hey @heleneh, hast du da was?

**Comment by heleneh** [comment]
ich arbeite dran! brauche aber noch ein wenig zeit

**Comment by stefanw** [comment]
Launcht jetzt ohne, sorry.

**Comment by arnese** [comment]
Ist inzwischen online.
