### ISSUE TITLE
Projektseiten: "Weitere Projekte" zeigt nichts an

### ISSUE THREAD

**Issue by arnese** [okfde/old.okfn.de#82]
Mir ist gerade aufgefallen, dass die Überschrift "Weitere Projekte" unterhalb der Projektseiten nichts anzeigt: z.B. https://okfn.de/projekte/fragdenstaat/
Sollen da thematisch verwandte oder irgendwelche anderen Projekte gezeigt werden?

**Comment by ffalt** [comment]
ah, good find. das ist ein überbleibsel. früher wurden da projekte aus dem "featured"-block der projekte-übersicht angezeigt, diese gibts aber nicht mehr.
ich habe die verbliebene überschrift auskommentiert, bis wir wissen ob und was wir da anzeigen wollen.

**Comment by arnese** [comment]
danke!
