### ISSUE TITLE
page.title bei Tag-Seiten

### ISSUE THREAD

**Issue by arnese** [okfde/old.okfn.de#83]
Nur eine Kleinigkeit: Mir ist aufgefallen, dass der Seitentitel von Tag-Seiten des Blogs (z.B. https://okfn.de/blog/tags/open-data-gesetz/) "page.title" ist - da könnte man vielleicht den Tag selbst als Seitentitel nehmen oder nur Open Knowledge Foundation.

**Comment by ffalt** [comment]
Danke, ein Bug in Folge des Übersetzungs-Plugins. Fixed mit einem Workaround im Plugin, es zeigt nun den Tag als Seitentitel.
