### ISSUE TITLE
Bürgerrechte vs. Grundrechte

### ISSUE THREAD

**Issue by stefanw** [okfde/old.okfn.de#84]
[Die Bürgerrechte auf unserer Seite](https://github.com/okfde/okfn.de/search?utf8=%E2%9C%93&q=B%C3%BCrgerrechte) sind in den meisten Fällen wahrscheinlich Grundrechte und wir sollten sie so nennen.

**Comment by arnese** [comment]
Überall da geändert, wo relevant
