### ISSUE TITLE
Facebook-Vorschau / opengraph

### ISSUE THREAD

**Issue by mneuschaefer** [okfde/old.okfn.de#86]
Wenn man einen Blogpost auf facebook teilt, erscheint das Titelbild des Artikels nicht in der Artikelvorschau bei fb, sondern nur die Bilder unter "Verwandte Beiträge". Das ist schade, denn die posts sind dadurch weniger sichtbar. Es scheint an den open graph tags zu liegen.

**Comment by ffalt** [comment]
ja, es lag an den open graph tags, denn: es gab überhaupt keine. ich habe die wichtigsten eingetragen und mit dem [sharing debugger](https://developers.facebook.com/tools/debug/sharing/ ) getestet.
